version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:14

jobs:
  build:
    executor: docker-executor
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            sudo apt update
            sudo apt install -y docker.io
            docker --version

      - run:
          name: Build Docker Image
          command: docker build -t network-assignment .

      - run:
          name: Run Container
          command: docker run -d -p 80:80 --name network-assignment network-assignment

    deploy:
    executor: docker-executor
    steps:
      - run:
          name: Deploy to EC2
          command: |
            ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST << "EOF"
            cd /var/www/html
            git pull origin main
            docker-compose up -d
            EOF


workflows:
  version: 2
  ci-cd:
    jobs:
      - build
      - deploy:
          requires:
            - build
