version: 2.1
jobs:
  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - add_ssh_keys:
          fingerprints:
            - "$AWS_PRIVATE_KEY"
      - run:
          name: Deploy to EC2
          command: |
            ssh -o StrictHostKeyChecking=no $EC2_USER@$EC2_HOST "
            cd /var/www/html &&
            git pull origin main &&
            docker-compose up -d"
workflows:
  deploy:
    jobs:
      - deploy
