version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/node:14

jobs:
  deploy:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Deploy to EC2
          command: |
            ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST <<\EOF
            cd /var/www/html
            git pull origin main
            docker-compose up -d
            EOF

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy