version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run:
          name: Show Pipeline Running
          command: echo "Pipeline is working successfully!"

workflows:
  version: 2
  simple-workflow:
    jobs:
      - test
