version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - add_ssh_keys:
          fingerprints:
            - "<your-key-fingerprint>"

      - run:
          name: Deploy to EC2
          command: |
            ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST << "EOF"
            cd /home/ec2-user
            docker-compose down
            git pull origin main
            docker-compose up -d
            EOF

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
